version: '3'

services:
  db:
    image: adann0/mariadb:armv7
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./mnt/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./mnt/www/example.org/cloud:/var/www/html
      - ./mnt/www/example.org/cloud/apps:/var/www/html/custom_apps
      - ./mnt/config/cloud:/var/www/html/config
      - ./mnt/data/cloud:/var/www/html/data
      - ./mnt/www/example.org/cloud/themes:/var/www/html/themes
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./mnt/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mnt/www/example.org/cloud:/var/www/html:ro
      - ./mnt/www/example.org/cloud/apps:/var/www/html/custom_apps:ro
      - ./mnt/config/nextcloud:/var/www/html/config:ro
      - ./mnt/data/cloud:/var/www/html/data:ro
      - ./mnt/www/example.org/cloud/themes:/var/www/html/themes:ro         
      - ./mnt/config/ssl/certs/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./mnt/config/letsencrypt/etc/live/example.org/fullchain.pem:/etc/letsencrypt/live/example.org/fullchain.pem
      - ./mnt/config/letsencrypt/etc/live/example.org/privkey.pem:/etc/letsencrypt/live/example.org/privkey.pem
      - ./mnt/www/example.org:/usr/share/nginx/html/example.org
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./mnt/www/example.org/cloud:/var/www/html
      - ./mnt/www/example.org/cloud/apps:/var/www/html/custom_apps
      - ./mnt/config/cloud:/var/www/html/config
      - ./mnt/data/cloud:/var/www/html/data
      - ./mnt/www/example.org/cloud/themes:/var/www/html/themes         
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  nginx-ldap-auth-daemon:
    image: adann0/nginx-ldap-auth-daemon:armv7
    container_name: rev3tk_nginx-ldap-auth-daemon
    restart: always
    ports:
      - 8888:8888

  openldap:
    image: adann0/openldap:armv7
    env_file:
      - openldap.env
    tty: true
    stdin_open: true
    volumes:
      - ./mnt/data/openldap/ldap:/var/lib/ldap
      - ./mnt/data/openldap/slapd:/etc/ldap/slapd.d
      - ./mnt/config/ssl/openldap:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    domainname: "example.org" # important: same as hostname
    hostname: "ldap.example.org"

  phpldapadmin:
    image: adann0/phpldapadmin:armv7
    env_file:
      - phpldapadmin.env
    volumes:
      - ./mnt/config/ssl/openldap:/container/service/ldap-client/assets/certs
      - ./mnt/config/ssl/phpldapadmin:/container/service/phpldapadmin/assets/apache2/certs
    ports:
      - "6443:443"
    depends_on:
      - openldap

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 1234:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mnt/data/portainer:/data

  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./mnt/config/hydra2:/config
      - ./mnt/data/media/movie/Deposit:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=Europe/Paris
    volumes:
      - ./mnt/config/deluge:/config
      - ./mnt/data/media/movie/Deposit:/downloads
    ports:
      - 8112:8112
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - RUN_OPTS=<run options here> #optional
    volumes:
      - ./mnt/config/jackett:/config
      - ./mnt/data/media/movie/Deposit:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  #jellyfin:
  #  image: jellyfin/jellyfin
  #  container_name: jellyfin
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=Europe/Paris
  #  volumes:
  #    - ./mnt/data/movie:/media
  #    - ./mnt/config/jellyfin:/config
  #  ports:
  #    - 8096:8096
  #  restart: unless-stopped

  daapd:
    image: linuxserver/daapd
    container_name: daapd
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./mnt/config/daapd:/config
      - ./mnt/data/media/music:/music
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./mnt/config/plex:/config
      - ./mnt/data/media/movie/Series:/data/tvshows
      - ./mnt/data/media/movie/Films:/data/movies
      - /tmp:/transcode
    restart: unless-stopped

  samba:
    image: adann0/samba-ldap:armv7
    environment:
     - SAMBA_LDAP_PASSWORD=secret
    ports:
     - "445:445"
    volumes:
     - ./mnt/config/samba/libnss-ldap.conf:/etc/libnss-ldap.conf:ro
     - ./mnt/config/samba/smb.conf:/etc/samba/smb.conf:ro
     - ./mnt/data/media:/media
    restart: always
    depends_on:
     - openldap

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./mnt/config/sonarr:/config
      - ./mnt/data/media/movie/Series:/tv
      - ./mnt/data/media/movie/Deposit:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./mnt/config/radarr:/config
      - ./mnt/data/media/movie/Films:/movies
      - ./mnt/data/media/movie/Deposit:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./mnt/config/bazarr:/config
      - ./mnt/data/media/movie/Films:/movies
      - ./mnt/data/media/movie/Series:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
